name: Lint Markdown Formatting

on: [push, pull_request]

jobs:
    lint-markdown:
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout repository
            uses: actions/checkout@v4

        -   name: Lint markdown formatting
            uses: DavidAnson/markdownlint-cli2-action@v20
            with:
                globs: '*.md'
                config: .markdownlint.json
